[general]
timeout=500
max-try=3

[lastfm]
username=XXX
security-profile=chrome116
method=api

[lastfm.api]
base-url=https://ws.audioscrobbler.com/2.0/
key='XXXXXXXXXXXXXXXXXXXXXXXX'
period=1week
diffusion=3
strategy=dfs
# topn or random
sample=random
random-sample-lambda=5.0
diffusion-lambda=0.25


[lastfm.web]
base-url=https://www.last.fm
recomm-path=/player/station/user/{username}/recommended
recomm-method=GET
recomm-accept=application/json, text/javascript, */*; q=0.01

[ncm]
cookie='XXXXX'
bind-method=http
bind-address=127.0.0.1
port=9900
