[general]
# timeout for fetching data from net 
timeout=5000
# TODO
max-try=3

[lastfm]
username=XXX
security-profile=chrome116
# api or web
method=api

[lastfm.api]
base-url=https://ws.audioscrobbler.com/2.0/
key='XXXXXXXXXXXXXXXXXXXXXXXX'
period=1week
diffusion=3
# dfs or bfs
strategy=dfs
# topn or random
sample=random
random-sample-lambda=5.0
diffusion-lambda=0.25
# score-beta=10.0


[lastfm.web]
base-url=https://www.last.fm
recomm-path=/player/station/user/{username}/recommended
recomm-method=GET
recomm-accept=application/json, text/javascript, */*; q=0.01

[ncm]
# nickname to ensure logining into right acccount
# for its hard to get userid for a user
username='XXXXX'
# storage cookie in a file
cookie-file='XXXXX'
# http or socket
bind-method=http
bind-address=127.0.0.1
# bind-method=socket
# bind-address=/tmp/mxrec.socket
port=9900
work-dir=
